### ISSUE TITLE
Chart 라이브러리 알아보기

### ISSUE THREAD

**Issue by lifeisegg123** [side-management/fe#7]
라이브러리 탐색 후 정리 및 발표

**Comment by catca** [comment]
### chart.js

[[GitHub - chartjs/Chart.js: Simple HTML5 Charts using the <canvas> tag](https://github.com/chartjs/Chart.js)](https://github.com/chartjs/Chart.js)

- 무료 라이센스
- canvas 기반
- 부드러운 애니메이션
- 깔끔한 디자인
- bar, line, pie 차트라면 다양한 커스텀 가능
- 꾸준한 업데이트(한달 전 업데이트) *****

### c3.js

[[GitHub - c3js/c3: A D3-based reusable chart library](https://github.com/c3js/c3)](https://github.com/c3js/c3)

- 무료 라이센스
- svg 기반
- 부드러운 애니메이션
- 깔끔한 디자인
- bar, line, pie 차트라면 다양한 커스텀 가능
- 3년 전 업데이트가 최신

### Apexchart.js

[[GitHub - apexcharts/apexcharts.js: 📊 Interactive JavaScript Charts built on SVG](https://github.com/apexcharts/apexcharts.js)](https://github.com/apexcharts/apexcharts.js)

- 무료 라이센스
- 자체 zoom,  pan, scroll 기능
- 파이썬으로 만든듯한 디자인
- 꾸준한 업데이트(한달 전 업데이트)

### 총평

사용자가 가장 많고, 업데이트가 지금까지 활발하고, 디자인도 깔끔한 chart.js가 괜찮다고 생각됨.
